---
title: "My Project"
author: "Jordan Starenky"
date: "2024-10-10"
output: "github_document"
---


```{r}
library(car)
library(dplyr)
library(tidyr)
library(ggplot2)
library(psych)
library(haven)
library(Rmisc)
library(rstatix)
library(emmeans)
library(bruceR)
library(dplyr)
library(labelled)


# Set working directory
setwd("/Users/jostarenky/Documents/GitHub/PSY329-Project")

# Read the TSV file
data <- read.table("/Users/jostarenky/Downloads/ICPSR_38964\ 2/DS0001/38964-0001-Data.tsv", sep = "\t", header = TRUE, fill = TRUE, quote = "")

# Write the data to a CSV file
write.csv(data, "38964-0001-Data.csv", row.names = FALSE)

#open file
data <- read.csv("/Users/jostarenky/Documents/GitHub/PSY329-Project/38964-0001-Data.csv")

#filter for desired variables
filtered_dataset <- data %>%
  select(SEX, MARSTAT, LONELY_A, LONELY_B, LONELY_C, HAPPY)

```

#Clean Data
```{r}
filtered_dataset <- filtered_dataset %>% filter(LONELY_A != "99", LONELY_B != "99", LONELY_C != "99")
filtered_dataset <- filtered_dataset %>% filter(SEX != "3")
filtered_dataset <- filtered_dataset %>% filter(MARSTAT != "99")
```

#Recode Variables
```{r}
filtered_dataset <- filtered_dataset%>%
  mutate_at(c('SEX'),funs(str_replace(., "1", "Male")))

filtered_dataset <- filtered_dataset%>%
  mutate_at(c('SEX'),funs(str_replace(., "2", "Female")))

filtered_dataset <- filtered_dataset%>%
  mutate_at(c('MARSTAT'),funs(str_replace(., "1", "Partnered")))

filtered_dataset <- filtered_dataset%>%
  mutate_at(c('MARSTAT'),funs(str_replace(., "2", "Single")))

filtered_dataset <- filtered_dataset%>%
  mutate_at(c('MARSTAT'),funs(str_replace(., "3", "Single")))

filtered_dataset <- filtered_dataset%>%
  mutate_at(c('MARSTAT'),funs(str_replace(., "4", "Single")))

filtered_dataset <- filtered_dataset%>%
  mutate_at(c('MARSTAT'),funs(str_replace(., "5", "Single")))

filtered_dataset <- filtered_dataset%>%
  mutate_at(c('MARSTAT'),funs(str_replace(., "6", "Partnered")))

filtered_dataset <- filtered_dataset %>%
  mutate(LONELINESS = rowSums(cbind(LONELY_A, LONELY_B, LONELY_C)))

```



#Normality
```{r}
ggplot(filtered_dataset, aes(x = LONELINESS)) + geom_histogram(binwidth = 1) + theme_classic()

ggplot(filtered_dataset, aes(x = LONELINESS)) + geom_density(adjust = 2)  + theme_classic()

qq<-ggplot(filtered_dataset, aes(sample = LONELINESS)) + geom_qq()  + theme_classic()

qq+ geom_qq_line()
```
```{r}
describe(filtered_dataset$LONELINESS)
#normal

describeBy(LONELINESS ~ SEX, data = filtered_dataset)
describeBy(LONELINESS ~ MARSTAT, data = filtered_dataset)

```

```{r}
#Variance
filtered_dataset%>%
  group_by(SEX) %>%
  summarize(variance = var(LONELINESS))

filtered_dataset%>%
  group_by(MARSTAT) %>%
  summarize(variance = var(LONELINESS))

```
```{r}
leveneTest(LONELINESS~MARSTAT, filtered_dataset)

MANOVA(filtered_dataset, dv = "LONELINESS", between = "MARSTAT")


leveneTest(LONELINESS~SEX, filtered_dataset)

MANOVA(filtered_dataset, dv = "LONELINESS", between = "SEX")

```

```{r}
filtered_dataset$Group <- ifelse(filtered_dataset$SEX == "Female" & filtered_dataset$MARSTAT == "Single", "Single Women", 
                     ifelse(filtered_dataset$SEX == "Male" & filtered_dataset$MARSTAT == "Single", "Single Men", 
                            ifelse(filtered_dataset$SEX == "Female" & filtered_dataset$MARSTAT == "Partnered", "Partnered Women", 
                                   "Partnered Men")))
```



```{r}

mod<-MANOVA(filtered_dataset, dv = "LONELINESS", between = c("SEX", "MARSTAT")) 

EMMEANS(mod, effect = "SEX", by = "MARSTAT", p.adjust = "none")

EMMEANS(mod, effect = "MARSTAT", by = "SEX", p.adjust = "none")
```
```{r}

plot<-summarySE(filtered_dataset, measurevar="LONELINESS", groupvars=c("SEX", "MARSTAT"))

plot

plot2<-summarySE(filtered_dataset, measurevar="LONELINESS", groupvars=c("Group"))

plot2

ggplot(plot, aes(x = SEX, y = LONELINESS, fill = SEX)) +
  geom_col() + facet_wrap(~ MARSTAT) + theme_bruce()

ggplot(plot2, aes(x = Group, y = LONELINESS, fill = Group)) +
  geom_col()  + theme_bruce() + theme(axis.text.x = element_text(angle = -10))
```
```{r}
#Recoding happiness variable (was reverse coded)
filtered_dataset$HAPPY <- 5 - filtered_dataset$HAPPY

```

```{r}
#checking assumptions for happiness
#normality plots
ggplot(filtered_dataset, aes(x = HAPPY)) + geom_histogram(binwidth = 1) + theme_classic()

ggplot(filtered_dataset, aes(x = HAPPY)) + geom_density(adjust = 2)  + theme_classic()

qq<-ggplot(filtered_dataset, aes(sample = HAPPY)) + geom_qq()  + theme_classic()

qq+ geom_qq_line()

#normality tests
describe(filtered_dataset$HAPPY)
#normal

describeBy(HAPPY ~ SEX, data = filtered_dataset)
describeBy(HAPPY ~ MARSTAT, data = filtered_dataset)

#variances
filtered_dataset%>%
  group_by(SEX) %>%
  summarize(variance = var(HAPPY))

filtered_dataset%>%
  group_by(MARSTAT) %>%
  summarize(variance = var(HAPPY))

```

```{r}
mod<-MANOVA(filtered_dataset, dv = "HAPPY", between = c("SEX", "MARSTAT")) 

EMMEANS(mod, effect = "SEX", by = "MARSTAT", p.adjust = "none")

EMMEANS(mod, effect = "MARSTAT", by = "SEX", p.adjust = "none")
```
```{r}
plot<-summarySE(filtered_dataset, measurevar="HAPPY", groupvars=c("SEX", "MARSTAT"))

plot

plot2<-summarySE(filtered_dataset, measurevar="HAPPY", groupvars=c("Group"))

plot2

ggplot(plot, aes(x = SEX, y = HAPPY, fill = SEX)) +
  geom_col() + facet_wrap(~ MARSTAT) + theme_bruce()

ggplot(plot2, aes(x = Group, y = HAPPY, fill = Group)) +
  geom_col()  + theme_bruce() + theme(axis.text.x = element_text(angle = -10))
```

